version: '3.9'
services:
  ms-1:
    build:
      context: ./ApiRest-taller-flisol-2024
      dockerfile: Dockerfile
    image: ms-1:1.0
    container_name: ApiRest-taller-flisol-2024
    ports:
      - "9595:9595"
    restart: always
    networks:
      - j-network 
networks: 
  j-network:
    driver: bridge
